import { DM } from './constants.js';
import { mkU, mkC, mkI, mkOb } from './helpers.js';

export const SEED_CLIENTS=[
  {id:1,name:"CzechBank s.r.o.",industry:"Finance",status:"active",since:"2026-01-14",contact:"Jan Nov\u00e1k \u00b7 jan.novak@czechbank.cz",tier:"Enterprise",description:"Mid-sized Czech bank on IBM AS/400. Active digital transformation initiative.",
    integrations:[{id:"gmail",connected:true,label:"finance@czechbank.cz"},{id:"postgres",connected:true,label:"prod-db:5432"},{id:"rest",connected:true,label:"https://api.czechbank.cz/v2"},{id:"mysql",connected:true,label:"crm-db:3306"}],
    environments:[{id:"ENV-CB-01",status:"active",created:"2026-01-14",integrationIds:["gmail","postgres","mysql"],agentIds:["AGT-001","AGT-004"],model:{...DM}},{id:"ENV-CB-02",status:"active",created:"2026-02-01",integrationIds:["postgres","rest"],agentIds:["AGT-006"],model:{...DM,modelId:"claude-opus-4-20250514"}}],
    workflows:[{id:"WF-CB-01",name:"Invoice Processing",type:"Financial Ops",description:"Invoices via Gmail, validated against PO DB, entered into PostgreSQL ERP.",agents:["AGT-001"],status:"automated"},{id:"WF-CB-02",name:"Compliance Monitoring",type:"Risk & Compliance",description:"Daily AML flag review, PostgreSQL + REST API risk scoring.",agents:["AGT-006"],status:"automated"},{id:"WF-CB-03",name:"CRM Record Sync",type:"CRM",description:"MySQL CRM and REST API partner portal sync.",agents:["AGT-004"],status:"automated"},{id:"WF-CB-04",name:"Monthly Reporting",type:"Reporting",description:"End-of-month PDF from PostgreSQL for board.",agents:[],status:"pending"}],
    notes:"GDPR mandatory \u2014 EU-hosted only.",
    onboarding:mkOb(4,{companySize:"250 employees",operationalFocus:"Retail and SME banking",complianceConstraints:"CNB regulation, AML directive, GDPR",automationGoal:"Eliminate manual data entry and accelerate compliance review",keyStakeholders:[{name:"Petr Hor\u00e1\u010dek",role:"CTO",authority:"Technical decisions"},{name:"Jana Svobodov\u00e1",role:"CFO",authority:"Invoice approvals over 50,000 CZK"},{name:"Martin K\u0159\u00ed\u017e",role:"Head of Compliance",authority:"All AML flags"}],painPoints:["2\u20134 hrs daily on manual invoice processing","AML reviews causing 48hr compliance backlog","CRM data 48hrs out of sync"],automationReadiness:78,intakeDate:"2026-01-10"},
      [{id:"WIC-CB-01",workflowId:"WF-CB-01",name:"Invoice Processing",owner:"Finance team (12 staff)",reviewer:"Jana Svobodov\u00e1",frequency:"~40 invoices/day",steps:[{order:1,actor:"Gmail",action:"Invoice arrives at finance@czechbank.cz",system:"Gmail",dataIn:"Email+PDF",dataOut:"Email metadata"},{order:2,actor:"Finance analyst",action:"Extract invoice number, vendor, amount, PO reference",system:"Manual",dataIn:"PDF",dataOut:"Fields"},{order:3,actor:"Finance analyst",action:"Query PostgreSQL PO table \u2014 validate within 5% tolerance",system:"PostgreSQL",dataIn:"PO ref, amount",dataOut:"Match/no-match"},{order:4,actor:"Finance analyst",action:"Enter into ERP or flag and notify vendor",system:"ERP",dataIn:"Invoice fields",dataOut:"ERP record"}],decisionPoints:[{condition:"Invoice > 50,000 CZK",action:"Escalate to CFO before processing",rule:"Hard rule"},{condition:"No matching PO found",action:"Flag invoice, do not process",rule:"Standard exception"},{condition:"Amount differs >5% from PO",action:"Flag for manual review",rule:"Tolerance rule"}],failureModes:["Duplicate invoices \u2014 INV-2024-8821","Missing PO references ~5%"],volumeNotes:"Month-end spike +60%.",successCriteria:"Invoice in ERP within 2hrs of receipt, or escalation triggered"}],
      {systems:[{id:"SYS-CB-01",name:"PostgreSQL ERP",role:"Primary invoice and transaction DB",connectionType:"Direct TCP",host:"prod-db.czechbank.internal",auth:"Service account \u2014 read/write invoices, po_records",schemas:[{table:"invoices",fields:["id","vendor_id","amount_czk","po_reference","status","created_at"]},{table:"po_records",fields:["id","po_number","vendor_id","approved_amount","tolerance_pct"]}],quirks:["Timestamps in CET not UTC","tolerance_pct defaults to 5 if NULL"]}],accessControls:[{role:"Invoice Agent",canRead:["invoices","po_records"],canWrite:["invoices"],cannotTouch:["transaction_logs","customers"]}]},
      [{id:"AD-CB-01",agentName:"Invoice Processor",personaName:"Vera",workflowRef:"WIC-CB-01",roleId:"analyst",activityId:"batch",personaTone:"Precise, professional, zero ambiguity",expertise:"Financial document processing, ERP data entry, anomaly detection",boundaries:["Never approves invoices autonomously","Never processes invoice over 50,000 CZK without CFO escalation","Flags duplicates \u2014 never resolves them"],successCriteria:"Invoice in ERP within 2hrs, or escalation triggered",escalationTarget:"Jana Svobodov\u00e1 (CFO) for >50k CZK"}])
  },
  {id:2,name:"Novak Industries",industry:"Manufacturing",status:"active",since:"2026-01-20",contact:"Tom\u00e1\u0161 Nov\u00e1k \u00b7 t.novak@novakindustries.cz",tier:"Enterprise",description:"Manufacturing group in Brno and Ostrava. Legacy SAP ERP, manual Excel sales pipeline.",
    integrations:[{id:"gmail",connected:true,label:"sales@novakindustries.cz"},{id:"rest",connected:true,label:"https://sap-api.novak.internal/v1"},{id:"mysql",connected:true,label:"crm.novak.internal:3306"}],
    environments:[{id:"ENV-NI-01",status:"active",created:"2026-01-20",integrationIds:["gmail","rest","mysql"],agentIds:["AGT-002"],model:{...DM,modelId:"claude-haiku-4-5"}}],
    workflows:[{id:"WF-NI-01",name:"Lead Qualification",type:"Sales",description:"Inbound email leads manually scored, updated in MySQL CRM.",agents:["AGT-002"],status:"automated"},{id:"WF-NI-02",name:"Inventory Alert",type:"Operations",description:"Daily SAP stock check, manual alerts.",agents:[],status:"pending"}],
    notes:"SAP REST API wrapper installed Jan 2026.",
    onboarding:mkOb(3,{companySize:"420 employees",operationalFocus:"Industrial component manufacturing, B2B sales",complianceConstraints:"Czech trade law, GDPR",automationGoal:"Accelerate sales pipeline",keyStakeholders:[{name:"Tom\u00e1\u0161 Nov\u00e1k",role:"CEO",authority:"Strategic decisions"},{name:"Radka Blahov\u00e1",role:"Sales Director",authority:"Lead scoring criteria"}],painPoints:["Sales team 3hrs/day qualifying leads","Inventory alerts delayed 24hrs"],automationReadiness:62,intakeDate:"2026-01-16"},
      [{id:"WIC-NI-01",workflowId:"WF-NI-01",name:"Lead Qualification",owner:"Sales team (8 reps)",reviewer:"Radka Blahov\u00e1",frequency:"~80 leads/week",steps:[{order:1,actor:"Gmail",action:"Inbound lead email arrives",system:"Gmail",dataIn:"Email",dataOut:"Contact info"},{order:2,actor:"Sales rep",action:"Score: company size, budget, urgency, fit (0\u201340)",system:"Excel",dataIn:"Email",dataOut:"Score"},{order:3,actor:"Sales rep",action:"Route: Hot>28, Warm 15\u201328, Cold<15",system:"Manual",dataIn:"Score",dataOut:"Action"},{order:4,actor:"Sales rep",action:"Update MySQL CRM",system:"MySQL",dataIn:"Lead details",dataOut:"CRM record"}],decisionPoints:[{condition:"Score > 28",action:"Notify Radka Blahov\u00e1 immediately",rule:"Scoring rubric v3"},{condition:"Lead is a distributor",action:"Downgrade to cold",rule:"Radka instruction 2026-03-15"},{condition:"Email mentions tender or RFQ",action:"Elevate to hot",rule:"High-intent signal"}],failureModes:["Too many false hot leads","Distributor emails not filtered"],volumeNotes:"Monday/Tuesday: 35% of weekly volume.",successCriteria:"All leads scored within 1hr. Hot leads notified within 15 minutes."}],
      {systems:[{id:"SYS-NI-01",name:"MySQL CRM",role:"Lead and customer management",connectionType:"Direct TCP",host:"crm.novak.internal",auth:"Service account \u2014 read/write leads",schemas:[{table:"leads",fields:["id","email","company","score","status","assigned_rep_id"]}],quirks:["leads.score stored as TEXT \u2014 cast on comparison"]}],accessControls:[{role:"Lead Qualifier",canRead:["leads"],canWrite:["leads"],cannotTouch:["customers"]}]},
      [{id:"AD-NI-01",agentName:"Lead Qualifier",personaName:"Max",workflowRef:"WIC-NI-01",roleId:"sales",activityId:"event",personaTone:"Direct, sales-focused, confident",expertise:"B2B lead scoring, manufacturing sector, CRM hygiene",boundaries:["Never makes pricing commitments","Never contacts leads directly \u2014 classification only"],successCriteria:"All leads scored within 1hr. Hot leads assigned within 15 minutes.",escalationTarget:"Radka Blahov\u00e1 for hot leads and edge cases."}])
  },
  {id:3,name:"MediCore Praha",industry:"Healthcare",status:"active",since:"2026-02-10",contact:"Dr. Eva Hor\u00e1\u010dkov\u00e1 \u00b7 e.hor\u00e1\u010dkov\u00e1@medicore.cz",tier:"Professional",description:"Private healthcare, 4 clinics in Prague. Google Drive records, PostgreSQL patient DB.",
    integrations:[{id:"gdrive",connected:true,label:"medicore-records (Shared Drive)"},{id:"postgres",connected:true,label:"patients-db:5432"}],
    environments:[{id:"ENV-MC-01",status:"active",created:"2026-02-10",integrationIds:["gdrive","postgres"],agentIds:["AGT-003"],model:{...DM,providerId:"offline",modelId:"qwen2-32b"}}],
    workflows:[{id:"WF-MC-01",name:"Report Generation",type:"Clinical Ops",description:"Weekly clinical summaries from PostgreSQL uploaded to Drive.",agents:["AGT-003"],status:"automated"},{id:"WF-MC-02",name:"Patient Follow-up",type:"Patient Care",description:"Post-appointment follow-up emails. ~120/week.",agents:[],status:"pending"}],
    notes:"GDPR and NZIS compliance. No PII outside environment.",
    onboarding:mkOb(2,{companySize:"62 staff, 4 clinics",operationalFocus:"General practice, specialist referrals",complianceConstraints:"GDPR, Czech NZIS \u2014 no patient data outside designated environment",automationGoal:"Automate clinical reporting",keyStakeholders:[{name:"Dr. Eva Hor\u00e1\u010dkov\u00e1",role:"Medical Director",authority:"All clinical decisions"},{name:"Tom\u00e1\u0161 P\u011bnkava",role:"IT Lead",authority:"System access, data governance"}],painPoints:["4hrs weekly compiling clinical reports","Follow-up emails inconsistent"],automationReadiness:41,intakeDate:"2026-02-05"},
      [{id:"WIC-MC-01",workflowId:"WF-MC-01",name:"Report Generation",owner:"Admin team",reviewer:"Dr. Eva Hor\u00e1\u010dkov\u00e1",frequency:"Weekly, Friday by 16:00",steps:[{order:1,actor:"Admin",action:"Query PostgreSQL for appointment data, past 7 days",system:"PostgreSQL",dataIn:"Date range",dataOut:"Records"},{order:2,actor:"Admin",action:"Aggregate by clinic, calculate completion and no-show rates",system:"Manual",dataIn:"Records",dataOut:"Metrics"},{order:3,actor:"Admin",action:"Anonymise \u2014 CLINIC_CODE-YYYYMMDD-SEQ",system:"Manual",dataIn:"Metrics",dataOut:"Anonymised report"},{order:4,actor:"Admin",action:"Upload to Drive /Clinical-Reports/Weekly",system:"Google Drive",dataIn:"Report",dataOut:"Uploaded file"}],decisionPoints:[{condition:"No-show rate > 20% for any clinic",action:"Flag with red indicator",rule:"Clinical threshold"},{condition:"Any PII detected in output",action:"Anonymise immediately \u2014 hard stop",rule:"NZIS compliance"}],failureModes:["Missing records due to 2hr system lag"],volumeNotes:"500\u2013700 records/week across 4 clinics.",successCriteria:"Report uploaded by Friday 16:00 with zero PII"}],
      {systems:[{id:"SYS-MC-01",name:"PostgreSQL Patient DB",role:"Appointment and patient records",connectionType:"Direct TCP",host:"patients-db.medicore.internal",auth:"Read-only \u2014 SELECT only",schemas:[{table:"appointments",fields:["id","clinic_code","doctor_id","appt_type","scheduled_at","completed_at","no_show"]}],quirks:["completed_at is NULL for no-shows \u2014 use no_show boolean","clinic_code is join key"]}],accessControls:[{role:"Report Generator",canRead:["appointments","doctors","clinics"],canWrite:["None \u2014 read-only"],cannotTouch:["patient_records","prescriptions","billing"]}]},
      [])
  },
  {id:4,name:"RetailMax Group",industry:"Retail",status:"onboarding",since:"2026-03-01",contact:"Lucie Kratochv\u00edlov\u00e1 \u00b7 l.kratochvilova@retailmax.cz",tier:"Professional",description:"E-commerce and brick-and-mortar retail. Gmail-heavy. Migrating to MySQL stack.",
    integrations:[{id:"gmail",connected:true,label:"support@retailmax.cz"},{id:"mysql",connected:false,label:""}],
    environments:[{id:"ENV-RM-01",status:"idle",created:"2026-03-01",integrationIds:["gmail"],agentIds:[],model:{...DM,modelId:"claude-haiku-4-5"}}],
    workflows:[{id:"WF-RM-01",name:"Email Classification",type:"Customer Ops",description:"~300 emails/day sorted: orders, complaints, returns, suppliers.",agents:[],status:"pending"}],
    notes:"MySQL 60% live. Target go-live: April 2026.",
    onboarding:mkOb(0,{companySize:"84 staff",operationalFocus:"Online and in-store retail",complianceConstraints:"GDPR for customer data",automationGoal:"Reduce customer service manual workload",keyStakeholders:[{name:"Lucie Kratochv\u00edlov\u00e1",role:"COO",authority:"All operational decisions"}],painPoints:["Customer service drowning in 300 emails/day","Inventory sync errors"],automationReadiness:29,intakeDate:"2026-02-25"},
      [],[],[])
  },
];

export const SEED_AGENTS=[
  {id:"AGT-001",name:"Invoice Processor",client:"CzechBank s.r.o.",role:"Data Analyst",activity:"Scheduled Batch Job",status:"running",tools:["Gmail","PostgreSQL"],lastRun:"2m ago",success:98,runs:1204,env:"ENV-CB-01",workflow:"WF-CB-01",credentials:mkC("anthropic"),usage:mkU(1204,820000,340000,100),intelligence:mkI({name:"Vera",tone:"Precise, professional",expertise:"Financial document processing",boundaries:["Never approves invoices","Escalates >50k CZK"]},"CzechBank invoice processing context \u2014 WIC-CB-01.",[{date:"2026-03-18",type:"preference",entry:"Finance team prefers summary PDF at batch end"},{date:"2026-03-14",type:"rule_update",entry:"Threshold updated 10k\u219215k CZK"}])},
  {id:"AGT-002",name:"Lead Qualifier",client:"Novak Industries",role:"Sales Agent",activity:"Event-Triggered",status:"running",tools:["REST API","Gmail","MySQL"],lastRun:"8m ago",success:94,runs:876,env:"ENV-NI-01",workflow:"WF-NI-01",credentials:mkC("anthropic"),usage:mkU(876,410000,180000,50),intelligence:mkI({name:"Max",tone:"Direct, sales-focused",expertise:"B2B lead scoring",boundaries:["Never contacts leads directly","No pricing commitments"]},"Novak Industries lead qualification context.",[{date:"2026-03-15",type:"correction",entry:"Distributor leads downgraded per Radka Blahov\u00e1"}])},
  {id:"AGT-003",name:"Report Generator",client:"MediCore Praha",role:"Report Generator",activity:"Scheduled Batch Job",status:"idle",tools:["Google Drive","PostgreSQL"],lastRun:"1h ago",success:100,runs:432,env:"ENV-MC-01",workflow:"WF-MC-01",credentials:mkC("offline"),usage:mkU(432,290000,120000,0),intelligence:mkI({name:"Clara",tone:"Clinical, structured",expertise:"Healthcare data, NZIS compliance",boundaries:["Zero PII in output","Read-only on patient DB"]},"MediCore clinical reporting context.",[{date:"2026-03-12",type:"preference",entry:"Dr. Hor\u00e1\u010dkov\u00e1 wants completion rate as first KPI"}])},
];
